apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: node-purcahse-service
  labels:
    app: node-purchase
spec:
  selector:
    app: node-purchase
  ports:
    - protocol: TCP
      port: 80        # Port exposed by the service
      targetPort: 3015  # Port on the container (update based on your app)
  type: NodePort  # Options: ClusterIP, NodePort, LoadBalancer
