apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: node-user-service
  labels:
    app: node-user
spec:
  selector:
    app: node-user
  ports:
    - protocol: TCP
      port: 80        # Port exposed by the service
      targetPort: 3005  # Port on the container (update based on your app)
  type: NodePort  # Options: ClusterIP, NodePort, LoadBalancer