server:
  http_listen_port: 9080

positions:
  filename: /var/log/promtail/positions.yaml

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log
