global:
  resolve_timeout: 5m

route:
  group_by: ['alert']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'default'

receivers:
  - name: 'default'
    email_configs:
    - to: 'abc@xyz'
      from: 'noreply@abc.com'
      smarthost: 'email-smtp.ap-south-1.amazonaws.com:587'
      auth_username: 'AKIA'
      auth_password: 'BAnpu'


