---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: production
  name: node-website-deployment
  labels:
    app: node-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-website
  template:
    metadata:
      labels:
        app: node-website
    spec:
      containers:
       - name: node-website
         image: 919314377239.dkr.ecr.ap-south-1.amazonaws.com/website:112
         envFrom:
          - secretRef:
                name: website-secret
         volumeMounts:
           - name: tz-config
             mountPath: /etc/localtime
         resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
         limits:
           memory: "500Mi"
           cpu: "200m"
      imagePullSecrets:
      - name: ecr-secret
      volumes:
       - name: tz-config
         hostPath:
          path: "/usr/share/zoneinfo/Asia/Calcutta"
