---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: production
  name: node-cms-deployment
  labels:
    app: node-cms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-cms
  template:
    metadata:
      labels:
        app: node-cms
    spec:
      containers:
        - name: node-cms
          image: 919314377239.dkr.ecr.ap-south-1.amazonaws.com/cms:36
      envFrom:
        - secretRef:
            name: cms-secret
      volumeMounts:
        - name: tz-config
          mountPath: /etc/localtime
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "500Mi"
          cpu: "200m"
      imagePullSecrets:
        - name: ecr-secret
      volumes:
        - name: tz-config
          hostPath:
            path: "/usr/share/zoneinfo/Asia/Calcutta"
