groups:
- name: node_exporter_alerts
  rules:
  - alert: HighCPUUsage
    expr: 100 - avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) > 80
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "High CPU usage detected on {{ $labels.instance }}"
      description: "CPU usage is above 80% for more than 5 minutes on instance {{ $labels.instance }}."

  - alert: HighMemoryUsage
    expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 80
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "High Memory usage detected on {{ $labels.instance }}"
      description: "Memory usage is above 80% for more than 5 minutes on instance {{ $labels.instance }}."
